In [1]:
import time
import pandas as pd
import numpy as np

CITY_DATA = { 'chicago': 'chicago.csv',
              'new york city': 'new_york_city.csv',
              'washington': 'washington.csv' }

def get_filters():
    """
    Asks user to specify a city, month, and day to analyze.

    Returns:
        (str) city - name of the city to analyze
        (str) month - name of the month to filter by, or "all" to apply no month filter
        (str) day - name of the day of week to filter by, or "all" to apply no day filter
    """
    print('Hello! Let\'s explore some US bikeshare data!')
    enter_city = input("enter city: ").lower()
    city = CITY_DATA[enter_city]


    print('-'*40)
    return city
    
def load_data(city):
    """
    Loads data for the specified city and filters by month and day if applicable.

    Args:
        (str) city - name of the city to analyze
        (str) month - name of the month to filter by, or "all" to apply no month filter
        (str) day - name of the day of week to filter by, or "all" to apply no day filter
    Returns:
        df - Pandas DataFrame containing city data filtered by month and day
    """
    df = pd.read_csv(city)
    df[["start_date", "start_time"]] = df["Start Time"].str.split(" ", expand = True)
    df[["start_year", "start_month", "start_day"]] = df["start_date"].str.split("-", expand = True)
    df["start_month"] = pd.to_numeric(df["start_month"])
    df["start_day"] = pd.to_numeric(df["start_day"])
    return df


def time_stats(df):
    """Displays statistics on the most frequent times of travel."""

    print('\nCalculating The Most Frequent Times of Travel...\n')
    start_time = time.time()

    # display the most common month
    most_common_month = df['start_month'].value_counts().head(1)

    # display the most common day of week
    most_common_day_week = df[["start_month", "start_day"]].value_counts().head(1)

    # display the most common start hour
    most_common_start_hour = df[["start_time"]].value_counts().head(1)
    
    print("---most common month--")
    print(most_common_month)
    print("---most common day of the week--")
    print(most_common_day_week)
    print("---most common start hour--")
    print(most_common_start_hour)
    #return most_common_month, most_common_day_week, most_common_start_hour


    print("\nThis took %s seconds." % (time.time() - start_time))
    print('-'*40)
    
#time_stats(data_df)

def station_stats(df):
    """Displays statistics on the most popular stations and trip."""

    print('\nCalculating The Most Popular Stations and Trip...\n')
    start_time = time.time()

    # display most commonly used start station
    most_common_start_station = df["Start Station"].value_counts().head(1)

    # display most commonly used end station
    most_common_end_station = df["End Station"].value_counts().head(1)

    # display most frequent combination of start station and end station trip

    popular_trip_start_end = df[["Start Station", "End Station"]].value_counts().head(1)
    
    print("----most start station----")
    print(most_common_start_station)
    print("----most common end station---")
    print(most_common_end_station)
    print("----frequent combination of start station and end station trip------")
    print(popular_trip_start_end)
    print("\nThis took %s seconds." % (time.time() - start_time))
    print('-'*40)
    
#station_stats(data_df)

def trip_duration_stats(df):
    """Displays statistics on the total and average trip duration."""

    print('\nCalculating Trip Duration...\n')
    start_time = time.time()

    # display total travel time
    total_travel_time = df["Trip Duration"].sum()

    # display mean travel time
    average_travel_time = df["Trip Duration"].mean()
    
    print("----total travel time----")
    print(total_travel_time)
    print("-----mean travel time-----")
    print(average_travel_time)

    print("\nThis took %s seconds." % (time.time() - start_time))
    print('-'*40)

#trip_duration_stats(data_df)


def user_stats(df):
    """Displays statistics on bikeshare users."""
# Display counts of user types
    print('\nCalculating User Stats...\n')
    start_time = time.time()
    if 'Gender' and 'Birth Year' in df.columns:
        count_user_info = df["User Type"].value_counts()


        # Display counts of gender
        gender_counts = df["Gender"].value_counts()

        # Display earliest, most recent, and most common year of birth
        earliest_birth_date = df["Birth Year"].min()
        most_recent = df["Birth Year"].max()
        most_common_birth_date = df["Birth Year"].value_counts().head(1)

        print("----count user typers----")
        print(count_user_info)
        print("----count gender--------")
        print(gender_counts)
        print("---earliest birth date----")
        print(earliest_birth_date)
        print("-----most recent birth date-----")
        print(most_recent)
        print("-----most common year of birth------")
        print(most_common_birth_date)
    
    else:
        count_user_info = df["User Type"].value_counts()
        print("----count user typers----")
        print(count_user_info)

            
    print("\nThis took %s seconds." % (time.time() - start_time))
    print('-'*40)
    
#user_stats(data_df)


def main():
    while True:
        city = get_filters()
        df = load_data(city)
        start_loc = 0
        while True:
            start_loc = start_loc + 5
            df_frame = df.iloc[0:start_loc]
            print(df_frame)
            view_display = input("do you wish to continue?: ").lower()
            if view_display != "yes":
                break
        
        df
        time_stats(df)
        station_stats(df)
        trip_duration_stats(df)
        user_stats(df)

        restart = input('\nWould you like to restart? Enter yes or no.\n')
        if restart.lower() != 'yes':
            break


if __name__ == "__main__":
    main()

Hello! Let's explore some US bikeshare data!
enter city: chicago
----------------------------------------
   Unnamed: 0           Start Time             End Time  Trip Duration  \
0     1423854  2017-06-23 15:09:32  2017-06-23 15:14:53            321
1      955915  2017-05-25 18:19:03  2017-05-25 18:45:53           1610
2        9031  2017-01-04 08:27:49  2017-01-04 08:34:45            416
3      304487  2017-03-06 13:49:38  2017-03-06 13:55:28            350
4       45207  2017-01-17 14:53:07  2017-01-17 15:02:01            534

                   Start Station                   End Station   User Type  \
0           Wood St & Hubbard St       Damen Ave & Chicago Ave  Subscriber
1            Theater on the Lake  Sheffield Ave & Waveland Ave  Subscriber
2             May St & Taylor St           Wood St & Taylor St  Subscriber
3  Christiana Ave & Lawrence Ave  St. Louis Ave & Balmoral Ave  Subscriber
4         Clark St & Randolph St  Desplaines St & Jackson Blvd  Subscriber

   Gender  Birth Year  start_date start_time start_year  start_month  \
0    Male      1992.0  2017-06-23   15:09:32       2017            6
1  Female      1992.0  2017-05-25   18:19:03       2017            5
2    Male      1981.0  2017-01-04   08:27:49       2017            1
3    Male      1986.0  2017-03-06   13:49:38       2017            3
4    Male      1975.0  2017-01-17   14:53:07       2017            1

   start_day
0         23
1         25
2          4
3          6
4         17
do you wish to continue?: yes
   Unnamed: 0           Start Time             End Time  Trip Duration  \
0     1423854  2017-06-23 15:09:32  2017-06-23 15:14:53            321
1      955915  2017-05-25 18:19:03  2017-05-25 18:45:53           1610
2        9031  2017-01-04 08:27:49  2017-01-04 08:34:45            416
3      304487  2017-03-06 13:49:38  2017-03-06 13:55:28            350
4       45207  2017-01-17 14:53:07  2017-01-17 15:02:01            534
5     1473887  2017-06-26 09:01:20  2017-06-26 09:11:06            586
6      961916  2017-05-26 09:41:44  2017-05-26 09:46:25            281
7       65924  2017-01-21 14:28:38  2017-01-21 14:40:41            723
8      606841  2017-04-20 16:08:51  2017-04-20 16:20:20            689
9      135470  2017-02-06 18:00:47  2017-02-06 18:09:00            493

                   Start Station                    End Station   User Type  \
0           Wood St & Hubbard St        Damen Ave & Chicago Ave  Subscriber
1            Theater on the Lake   Sheffield Ave & Waveland Ave  Subscriber
2             May St & Taylor St            Wood St & Taylor St  Subscriber
3  Christiana Ave & Lawrence Ave   St. Louis Ave & Balmoral Ave  Subscriber
4         Clark St & Randolph St   Desplaines St & Jackson Blvd  Subscriber
5   Clinton St & Washington Blvd           Canal St & Taylor St  Subscriber
6          Ashland Ave & Lake St           Wood St & Hubbard St  Subscriber
7     Larrabee St & Kingsbury St     Larrabee St & Armitage Ave    Customer
8         Sedgwick St & Huron St  Halsted St & Blackhawk St (*)  Subscriber
9   Stetson Ave & South Water St   Clinton St & Washington Blvd  Subscriber

   Gender  Birth Year  start_date start_time start_year  start_month  \
0    Male      1992.0  2017-06-23   15:09:32       2017            6
1  Female      1992.0  2017-05-25   18:19:03       2017            5
2    Male      1981.0  2017-01-04   08:27:49       2017            1
3    Male      1986.0  2017-03-06   13:49:38       2017            3
4    Male      1975.0  2017-01-17   14:53:07       2017            1
5    Male      1990.0  2017-06-26   09:01:20       2017            6
6  Female      1983.0  2017-05-26   09:41:44       2017            5
7     NaN         NaN  2017-01-21   14:28:38       2017            1
8    Male      1984.0  2017-04-20   16:08:51       2017            4
9    Male      1979.0  2017-02-06   18:00:47       2017            2

   start_day
0         23
1         25
2          4
3          6
4         17
5         26
6         26
7         21
8         20
9          6
do you wish to continue?: yes
    Unnamed: 0           Start Time             End Time  Trip Duration  \
0      1423854  2017-06-23 15:09:32  2017-06-23 15:14:53            321
1       955915  2017-05-25 18:19:03  2017-05-25 18:45:53           1610
2         9031  2017-01-04 08:27:49  2017-01-04 08:34:45            416
3       304487  2017-03-06 13:49:38  2017-03-06 13:55:28            350
4        45207  2017-01-17 14:53:07  2017-01-17 15:02:01            534
5      1473887  2017-06-26 09:01:20  2017-06-26 09:11:06            586
6       961916  2017-05-26 09:41:44  2017-05-26 09:46:25            281
7        65924  2017-01-21 14:28:38  2017-01-21 14:40:41            723
8       606841  2017-04-20 16:08:51  2017-04-20 16:20:20            689
9       135470  2017-02-06 18:00:47  2017-02-06 18:09:00            493
10      175805  2017-02-15 07:09:55  2017-02-15 07:14:56            301
11       71678  2017-01-22 15:15:45  2017-01-22 15:31:02            917
12       19061  2017-01-08 16:03:00  2017-01-08 16:07:37            277
13     1023296  2017-05-30 15:46:18  2017-05-30 15:52:12            354
14      611000  2017-04-20 19:26:33  2017-04-20 19:35:08            515

                     Start Station                      End Station  \
0             Wood St & Hubbard St          Damen Ave & Chicago Ave
1              Theater on the Lake     Sheffield Ave & Waveland Ave
2               May St & Taylor St              Wood St & Taylor St
3    Christiana Ave & Lawrence Ave     St. Louis Ave & Balmoral Ave
4           Clark St & Randolph St     Desplaines St & Jackson Blvd
5     Clinton St & Washington Blvd             Canal St & Taylor St
6            Ashland Ave & Lake St             Wood St & Hubbard St
7       Larrabee St & Kingsbury St       Larrabee St & Armitage Ave
8           Sedgwick St & Huron St    Halsted St & Blackhawk St (*)
9     Stetson Ave & South Water St     Clinton St & Washington Blvd
10            Broadway & Barry Ave         Wilton Ave & Belmont Ave
11  Southport Ave & Wellington Ave           Clark St & Schiller St
12           Green St & Madison St         Ada St & Washington Blvd
13      Larrabee St & Kingsbury St                Clark St & Elm St
14           Canal St & Madison St  Racine Ave (May St) & Fulton St

     User Type  Gender  Birth Year  start_date start_time start_year  \
0   Subscriber    Male      1992.0  2017-06-23   15:09:32       2017
1   Subscriber  Female      1992.0  2017-05-25   18:19:03       2017
2   Subscriber    Male      1981.0  2017-01-04   08:27:49       2017
3   Subscriber    Male      1986.0  2017-03-06   13:49:38       2017
4   Subscriber    Male      1975.0  2017-01-17   14:53:07       2017
5   Subscriber    Male      1990.0  2017-06-26   09:01:20       2017
6   Subscriber  Female      1983.0  2017-05-26   09:41:44       2017
7     Customer     NaN         NaN  2017-01-21   14:28:38       2017
8   Subscriber    Male      1984.0  2017-04-20   16:08:51       2017
9   Subscriber    Male      1979.0  2017-02-06   18:00:47       2017
10  Subscriber  Female      1993.0  2017-02-15   07:09:55       2017
11  Subscriber    Male      1964.0  2017-01-22   15:15:45       2017
12  Subscriber    Male      1961.0  2017-01-08   16:03:00       2017
13  Subscriber    Male      1985.0  2017-05-30   15:46:18       2017
14  Subscriber    Male      1984.0  2017-04-20   19:26:33       2017

    start_month  start_day
0             6         23
1             5         25
2             1          4
3             3          6
4             1         17
5             6         26
6             5         26
7             1         21
8             4         20
9             2          6
10            2         15
11            1         22
12            1          8
13            5         30
14            4         20

do you wish to continue?: no

Calculating The Most Frequent Times of Travel...

---most common month--
6    98081
Name: start_month, dtype: int64
---most common day of the week--
start_month  start_day
6            24           3841
dtype: int64
---most common start hour--
start_time
16:49:13      24
dtype: int64

This took 2.4418773651123047 seconds.
----------------------------------------

Calculating The Most Popular Stations and Trip...

----most start station----
Streeter Dr & Grand Ave    6911
Name: Start Station, dtype: int64
----most common end station---
Streeter Dr & Grand Ave    7512
Name: End Station, dtype: int64
----frequent combination of start station and end station trip------
Start Station              End Station
Lake Shore Dr & Monroe St  Streeter Dr & Grand Ave    854
dtype: int64

This took 0.4006054401397705 seconds.
----------------------------------------

Calculating Trip Duration...

----total travel time----
280871787
-----mean travel time-----
936.23929

This took 0.19410443305969238 seconds.
----------------------------------------

Calculating User Stats...

----count user typers----
Subscriber    238889
Customer       61110
Dependent          1
Name: User Type, dtype: int64
----count gender--------
Male      181190
Female     57758
Name: Gender, dtype: int64
---earliest birth date----
1899.0
-----most recent birth date-----
2016.0
-----most common year of birth------
1989.0    14666
Name: Birth Year, dtype: int64

This took 0.19433307647705078 seconds.
----------------------------------------

Would you like to restart? Enter yes or no.
yes
Hello! Let's explore some US bikeshare data!
enter city: washington
----------------------------------------
   Unnamed: 0           Start Time             End Time  Trip Duration  \
0     1621326  2017-06-21 08:36:34  2017-06-21 08:44:43        489.066
1      482740  2017-03-11 10:40:00  2017-03-11 10:46:00        402.549
2     1330037  2017-05-30 01:02:59  2017-05-30 01:13:37        637.251
3      665458  2017-04-02 07:48:35  2017-04-02 08:19:03       1827.341
4     1481135  2017-06-10 08:36:28  2017-06-10 09:02:17       1549.427

                                 Start Station                   End Station  \
0                         14th & Belmont St NW                15th & K St NW
1                   Yuma St & Tenley Circle NW  Connecticut Ave & Yuma St NW
2               17th St & Massachusetts Ave NW                 5th & K St NW
3             Constitution Ave & 2nd St NW/DOL    M St & Pennsylvania Ave NW
4  Henry Bacon Dr & Lincoln Memorial Circle NW         Maine Ave & 7th St SW

    User Type  start_date start_time start_year  start_month  start_day
0  Subscriber  2017-06-21   08:36:34       2017            6         21
1  Subscriber  2017-03-11   10:40:00       2017            3         11
2  Subscriber  2017-05-30   01:02:59       2017            5         30
3    Customer  2017-04-02   07:48:35       2017            4          2
4  Subscriber  2017-06-10   08:36:28       2017            6         10
do you wish to continue?: no

Calculating The Most Frequent Times of Travel...

---most common month--
6    68339
Name: start_month, dtype: int64
---most common day of the week--
start_month  start_day
4            15           2851
dtype: int64
---most common start hour--
start_time
17:41:00      277
dtype: int64

This took 0.5838160514831543 seconds.
----------------------------------------

Calculating The Most Popular Stations and Trip...

----most start station----
Columbus Circle / Union Station    5656
Name: Start Station, dtype: int64
----most common end station---
Columbus Circle / Union Station    6048
Name: End Station, dtype: int64
----frequent combination of start station and end station trip------
Start Station              End Station
Jefferson Dr & 14th St SW  Jefferson Dr & 14th St SW    673
dtype: int64

This took 0.31582164764404297 seconds.
----------------------------------------

Calculating Trip Duration...

----total travel time----
371183985.484
-----mean travel time-----
1237.2799516133446

This took 0.03929615020751953 seconds.
----------------------------------------

Calculating User Stats...

----count user typers----
Subscriber    220786
Customer       79214
Name: User Type, dtype: int64

This took 0.0535130500793457 seconds.
----------------------------------------

Would you like to restart? Enter yes or no.
no